name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'   # Executa em qualquer branch exceto na master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Create Pull Request to master
        if: success()
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Automated build and test successful"
          branch: "ci-cd-branch"
          base: "master"
          title: "Automated Pull Request"
          body: "Automated pull request generated after successful build and test"
          token: ${{ secrets.CREATE_PULL_TOKEN }}
