name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'   # Executa em qualquer branch exceto na master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Open PR
        id: open_pr
        if: github.ref != 'refs/heads/master'
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.CREATE_PULL_TOKEN }}
          from-branch: feature/gitactions
          to-branch: master
          repository-owner: M4rcioOliveira
          repository: Integration_GitHubActions-Java-Spring

      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}

      - name: Call Email API on Success
        if: success()
        run: |
          curl -X POST https://webhook.site/74a57e71-ce1b-4aba-be02-260f82543d8b \
            -H "Content-Type: application/json" \
            -d '{"to": "recipient@example.com", "subject": "Build Success", "body": "The CI/CD pipeline has succeeded." }'
