name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'   # Executa em qualquer branch exceto na master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Open PR
        id: open_pr
        if: github.ref != 'refs/heads/master'
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.CREATE_PULL_TOKEN }}
          from-branch: feature/gitactions
          to-branch: master
          repository-owner: M4rcioOliveira
          repository: Integration_GitHubActions-Java-Spring

      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}